stages:
- docker
- test
- publish

variables:
  CONTAINER_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE: $CONTAINER_REGISTRY/taig-github/spjv
  DOCKER_DRIVER: overlay2

docker:
  stage: docker
  image: docker
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_REGISTRY
  - docker pull $CONTAINER_IMAGE:latest || true
  - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF_NAME .
  - docker push $CONTAINER_IMAGE

test-format:
  stage: test
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  script:
  - sbt scalafmtCheckAll

test-suite:
  stage: test
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  script:
  - sbt -Dmode=strict coverage test coverageReport
  artifacts:
      paths:
        - /builds/taig-github/spjv/target/scala-2.13/scoverage-report/

publish-artifacts:
  stage: publish
  image: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  script:
  - sbt assembly
  artifacts:
      paths:
        - /builds/taig-github/spjv/target/scala-2.13/spjv-*.jar